### PR TITLE
feat: add basic Redux dev plugin

### PR DESCRIPTION
**Pull request by dannyBies**
I'd like to be able to view my redux store using a dev-plugin. I've created a basic version that will show the latest values in the store. Ideally this would be solved in the middleware layer so we have more access to useful information as with the current approach you can only get the current store value.

Unfortunately I don't have enough time to fully integrate Redux with a dev-plugin but I'm hoping this PR can be a V0.1 and someone else can improve upon this foundation.

https://github.com/expo/dev-plugins/assets/3967506/1a3ce152-c671-4aff-94c6-22103cadee43

### CODE REVIEW

**Comment by benjaminkomen** [comment]
Maybe you can remove the changes to the build directories of the other dev-plugins from this PR, to keep it more focused?

**Review by Kudo — APPROVED** [review]
thanks for the work. it looks good for the first version and scaffolding for redux plugin. please help to revert the changes to other plugins and we are good to merge this pr.

**Comment by dannyBies** [comment]
Thanks! I've updated the PR to remove the build artifacts.

**Comment by benjaminkomen** [comment]
Can we merge this PR?

**Comment by c2tarun** [comment]
Can we please merge this PR?

**Review by Kudo — APPROVED** [review]

**Comment by Kudo** [comment]
@dannyBies sorry for long waiting. the plugin is published in `@dev-plugin/redux`. i was struggling to find bandwidth to support broader plugins and then realized that be honest it is to difficult for me to review all prs and publish fixes in a scale way. i think a better way is to host new plugins in individual's npm accounts. i'm turning this repository as a gallery for people to promote new plugins as described in the [README](https://github.com/expo/dev-plugins/blob/main/README.md#contributions).

at this moment, i'm happy to help the `@dev-plugins/redux` transition when you get a chance to create a plugin in your account. sorry for this inconvenience and thanks again for your awesome work.

**Pull request merged**
